






state={
    element:null,
    iframe:document.querySelector('iframe'),
    get contentwindow() {
        return this.iframe.contentWindow
    },
    get contentDocument() {
        return this.iframe.contentDocument
    },
    col:document.querySelector(`.${init.class_names.col}`),
    x:0,y:0,
    move:false,
    offx:0,
    offy:0,
    range_slider:document.querySelector("#myRange"),
    range_slider_value:document.querySelector("#demo"),
    search_bar:document.querySelector('.search_bar'),
    view_div_up:document.querySelector('.iframe-width-changer'),
    view_div:document.querySelector('.iframe-width-changer-inner'),
    worker:{},
    class_style_demo:{
        "align": {
            "alignContent": "",
            "alignItems": "",
            "alignSelf": ""
        },
        "alignment": "",
        "all": "",
        "animation": {
            "animation": "",
            "animationDelay": "",
            "animationDirection": "",
            "animationDuration": "",
            "animationFillMode": "",
            "animationIterationCount": "",
            "animationName": "",
            "animationPlayState": "",
            "animationTimingFunction": ""
        },
        "appearance": "",
        "backdrop": "",
        "backface": "",
        "background": {
            "background": "",
            "backgroundAttachment": "",
            "backgroundBlendMode": "",
            "backgroundClip": "",
            "backgroundColor": "",
            "backgroundImage": "",
            "backgroundOrigin": "",
            "backgroundPosition": "",
            "backgroundPositionX": "",
            "backgroundPositionY": "",
            "backgroundRepeat": "",
            "backgroundRepeatX": "",
            "backgroundRepeatY": "",
            "backgroundSize": ""
        },
        "baseline": "",
        "block": "",
        "border": {
            "border": "",
            "borderBlockEnd": "",
            "borderBlockEndColor": "",
            "borderBlockEndStyle": "",
            "borderBlockEndWidth": "",
            "borderBlockStart": "",
            "borderBlockStartColor": "",
            "borderBlockStartStyle": "",
            "borderBlockStartWidth": "",
            "borderBottom": "",
            "borderBottomColor": "",
            "borderBottomLeftRadius": "",
            "borderBottomRightRadius": "",
            "borderBottomStyle": "",
            "borderBottomWidth": "",
            "borderCollapse": "",
            "borderColor": "",
            "borderImage": "",
            "borderImageOutset": "",
            "borderImageRepeat": "",
            "borderImageSlice": "",
            "borderImageSource": "",
            "borderImageWidth": "",
            "borderInlineEnd": "",
            "borderInlineEndColor": "",
            "borderInlineEndStyle": "",
            "borderInlineEndWidth": "",
            "borderInlineStart": "",
            "borderInlineStartColor": "",
            "borderInlineStartStyle": "",
            "borderInlineStartWidth": "",
            "borderLeft": "",
            "borderLeftColor": "",
            "borderLeftStyle": "",
            "borderLeftWidth": "",
            "borderRadius": "",
            "borderRight": "",
            "borderRightColor": "",
            "borderRightStyle": "",
            "borderRightWidth": "",
            "borderSpacing": "",
            "borderStyle": "",
            "borderTop": "",
            "borderTopColor": "",
            "borderTopLeftRadius": "",
            "borderTopRightRadius": "",
            "borderTopStyle": "",
            "borderTopWidth": "",
            "borderWidth": ""
        },
        "bottom": "",
        "box": {
            "boxShadow": "",
            "boxSizing": ""
        },
        "break": {
            "breakAfter": "",
            "breakBefore": "",
            "breakInside": ""
        },
        "buffered": "",
        "caption": "",
        "caret": "",
        "clear": "",
        "clip": {
            "clip": "",
            "clipPath": "",
            "clipRule": ""
        },
        "color": {
            "color": "",
            "colorInterpolation": "",
            "colorInterpolationFilters": "",
            "colorRendering": "",
            "colorScheme": ""
        },
        "column": {
            "columnCount": "",
            "columnFill": "",
            "columnGap": "",
            "columnRule": "",
            "columnRuleColor": "",
            "columnRuleStyle": "",
            "columnRuleWidth": "",
            "columnSpan": "",
            "columnWidth": ""
        },
        "columns": "",
        "contain": {
            "contain": "",
            "containIntrinsicSize": ""
        },
        "content": {
            "content": "",
            "contentVisibility": ""
        },
        "counter": {
            "counterIncrement": "",
            "counterReset": "",
            "counterSet": ""
        },
        "css": {
            "cssFloat": "",
            "cssText": ""
        },
        "cursor": "",
        "cx": "",
        "cy": "",
        "d": "",
        "direction": "",
        "display": "",
        "dominant": "",
        "empty": "",
        "fill": {
            "fill": "",
            "fillOpacity": "",
            "fillRule": ""
        },
        "filter": "",
        "flex": {
            "flex": "",
            "flexBasis": "",
            "flexDirection": "",
            "flexFlow": "",
            "flexGrow": "",
            "flexShrink": "",
            "flexWrap": ""
        },
        "float": "",
        "flood": {
            "floodColor": "",
            "floodOpacity": ""
        },
        "font": {
            "font": "",
            "fontDisplay": "",
            "fontFamily": "",
            "fontFeatureSettings": "",
            "fontKerning": "",
            "fontOpticalSizing": "",
            "fontSize": "",
            "fontStretch": "",
            "fontStyle": "",
            "fontVariant": "",
            "fontVariantCaps": "",
            "fontVariantEastAsian": "",
            "fontVariantLigatures": "",
            "fontVariantNumeric": "",
            "fontVariationSettings": "",
            "fontWeight": ""
        },
        "gap": "",
        "grid": {
            "grid": "",
            "gridArea": "",
            "gridAutoColumns": "",
            "gridAutoFlow": "",
            "gridAutoRows": "",
            "gridColumn": "",
            "gridColumnEnd": "",
            "gridColumnGap": "",
            "gridColumnStart": "",
            "gridGap": "",
            "gridRow": "",
            "gridRowEnd": "",
            "gridRowGap": "",
            "gridRowStart": "",
            "gridTemplate": "",
            "gridTemplateAreas": "",
            "gridTemplateColumns": "",
            "gridTemplateRows": ""
        },
        "height": "",
        "hyphens": "",
        "image": {
            "imageOrientation": "",
            "imageRendering": ""
        },
        "inherits": "",
        "initial": "",
        "inline": "",
        "isolation": "",
        "justify": {
            "justifyContent": "",
            "justifyItems": "",
            "justifySelf": ""
        },
        "left": "",
        "length": "",
        "letter": "",
        "lighting": "",
        "line": {
            "lineBreak": "",
            "lineHeight": ""
        },
        "list": {
            "listStyle": "",
            "listStyleImage": "",
            "listStylePosition": "",
            "listStyleType": ""
        },
        "margin": {
            "margin": "",
            "marginBlockEnd": "",
            "marginBlockStart": "",
            "marginBottom": "",
            "marginInlineEnd": "",
            "marginInlineStart": "",
            "marginLeft": "",
            "marginRight": "",
            "marginTop": ""
        },
        "marker": {
            "marker": "",
            "markerEnd": "",
            "markerMid": "",
            "markerStart": ""
        },
        "mask": {
            "mask": "",
            "maskType": ""
        },
        "max": {
            "maxBlockSize": "",
            "maxHeight": "",
            "maxInlineSize": "",
            "maxWidth": "",
            "maxZoom": ""
        },
        "min": {
            "minBlockSize": "",
            "minHeight": "",
            "minInlineSize": "",
            "minWidth": "",
            "minZoom": ""
        },
        "mix": "",
        "object": {
            "objectFit": "",
            "objectPosition": ""
        },
        "offset": {
            "offset": "",
            "offsetDistance": "",
            "offsetPath": "",
            "offsetRotate": ""
        },
        "opacity": "",
        "order": "",
        "orientation": "",
        "orphans": "",
        "outline": {
            "outline": "",
            "outlineColor": "",
            "outlineOffset": "",
            "outlineStyle": "",
            "outlineWidth": ""
        },
        "overflow": {
            "overflow": "",
            "overflowAnchor": "",
            "overflowWrap": "",
            "overflowX": "",
            "overflowY": ""
        },
        "overscroll": {
            "overscrollBehavior": "",
            "overscrollBehaviorBlock": "",
            "overscrollBehaviorInline": "",
            "overscrollBehaviorX": "",
            "overscrollBehaviorY": ""
        },
        "padding": {
            "padding": "",
            "paddingBlockEnd": "",
            "paddingBlockStart": "",
            "paddingBottom": "",
            "paddingInlineEnd": "",
            "paddingInlineStart": "",
            "paddingLeft": "",
            "paddingRight": "",
            "paddingTop": ""
        },
        "page": {
            "page": "",
            "pageBreakAfter": "",
            "pageBreakBefore": "",
            "pageBreakInside": "",
            "pageOrientation": ""
        },
        "paint": "",
        "parent": "",
        "perspective": {
            "perspective": "",
            "perspectiveOrigin": ""
        },
        "place": {
            "placeContent": "",
            "placeItems": "",
            "placeSelf": ""
        },
        "pointer": "",
        "position": "",
        "quotes": "",
        "r": "",
        "resize": "",
        "right": "",
        "row": "",
        "ruby": "",
        "rx": "",
        "ry": "",
        "scroll": {
            "scrollBehavior": "",
            "scrollMargin": "",
            "scrollMarginBlock": "",
            "scrollMarginBlockEnd": "",
            "scrollMarginBlockStart": "",
            "scrollMarginBottom": "",
            "scrollMarginInline": "",
            "scrollMarginInlineEnd": "",
            "scrollMarginInlineStart": "",
            "scrollMarginLeft": "",
            "scrollMarginRight": "",
            "scrollMarginTop": "",
            "scrollPadding": "",
            "scrollPaddingBlock": "",
            "scrollPaddingBlockEnd": "",
            "scrollPaddingBlockStart": "",
            "scrollPaddingBottom": "",
            "scrollPaddingInline": "",
            "scrollPaddingInlineEnd": "",
            "scrollPaddingInlineStart": "",
            "scrollPaddingLeft": "",
            "scrollPaddingRight": "",
            "scrollPaddingTop": "",
            "scrollSnapAlign": "",
            "scrollSnapStop": "",
            "scrollSnapType": ""
        },
        "shape": {
            "shapeImageThreshold": "",
            "shapeMargin": "",
            "shapeOutside": "",
            "shapeRendering": ""
        },
        "size": "",
        "speak": "",
        "src": "",
        "stop": {
            "stopColor": "",
            "stopOpacity": ""
        },
        "stroke": {
            "stroke": "",
            "strokeDasharray": "",
            "strokeDashoffset": "",
            "strokeLinecap": "",
            "strokeLinejoin": "",
            "strokeMiterlimit": "",
            "strokeOpacity": "",
            "strokeWidth": ""
        },
        "syntax": "",
        "tab": "",
        "table": "",
        "text": {
            "textAlign": "",
            "textAlignLast": "",
            "textAnchor": "",
            "textCombineUpright": "",
            "textDecoration": "",
            "textDecorationColor": "",
            "textDecorationLine": "",
            "textDecorationSkipInk": "",
            "textDecorationStyle": "",
            "textIndent": "",
            "textOrientation": "",
            "textOverflow": "",
            "textRendering": "",
            "textShadow": "",
            "textSizeAdjust": "",
            "textTransform": "",
            "textUnderlinePosition": ""
        },
        "top": "",
        "touch": "",
        "transform": {
            "transform": "",
            "transformBox": "",
            "transformOrigin": "",
            "transformStyle": ""
        },
        "transition": {
            "transition": "",
            "transitionDelay": "",
            "transitionDuration": "",
            "transitionProperty": "",
            "transitionTimingFunction": ""
        },
        "unicode": {
            "unicodeBidi": "",
            "unicodeRange": ""
        },
        "user": {
            "userSelect": "",
            "userZoom": ""
        },
        "vector": "",
        "vertical": "",
        "visibility": "",
        "webkit": {
            "webkitAlignContent": "",
            "webkitAlignItems": "",
            "webkitAlignSelf": "",
            "webkitAnimation": "",
            "webkitAnimationDelay": "",
            "webkitAnimationDirection": "",
            "webkitAnimationDuration": "",
            "webkitAnimationFillMode": "",
            "webkitAnimationIterationCount": "",
            "webkitAnimationName": "",
            "webkitAnimationPlayState": "",
            "webkitAnimationTimingFunction": "",
            "webkitAppRegion": "",
            "webkitAppearance": "",
            "webkitBackfaceVisibility": "",
            "webkitBackgroundClip": "",
            "webkitBackgroundOrigin": "",
            "webkitBackgroundSize": "",
            "webkitBorderAfter": "",
            "webkitBorderAfterColor": "",
            "webkitBorderAfterStyle": "",
            "webkitBorderAfterWidth": "",
            "webkitBorderBefore": "",
            "webkitBorderBeforeColor": "",
            "webkitBorderBeforeStyle": "",
            "webkitBorderBeforeWidth": "",
            "webkitBorderBottomLeftRadius": "",
            "webkitBorderBottomRightRadius": "",
            "webkitBorderEnd": "",
            "webkitBorderEndColor": "",
            "webkitBorderEndStyle": "",
            "webkitBorderEndWidth": "",
            "webkitBorderHorizontalSpacing": "",
            "webkitBorderImage": "",
            "webkitBorderRadius": "",
            "webkitBorderStart": "",
            "webkitBorderStartColor": "",
            "webkitBorderStartStyle": "",
            "webkitBorderStartWidth": "",
            "webkitBorderTopLeftRadius": "",
            "webkitBorderTopRightRadius": "",
            "webkitBorderVerticalSpacing": "",
            "webkitBoxAlign": "",
            "webkitBoxDecorationBreak": "",
            "webkitBoxDirection": "",
            "webkitBoxFlex": "",
            "webkitBoxOrdinalGroup": "",
            "webkitBoxOrient": "",
            "webkitBoxPack": "",
            "webkitBoxReflect": "",
            "webkitBoxShadow": "",
            "webkitBoxSizing": "",
            "webkitClipPath": "",
            "webkitColumnBreakAfter": "",
            "webkitColumnBreakBefore": "",
            "webkitColumnBreakInside": "",
            "webkitColumnCount": "",
            "webkitColumnGap": "",
            "webkitColumnRule": "",
            "webkitColumnRuleColor": "",
            "webkitColumnRuleStyle": "",
            "webkitColumnRuleWidth": "",
            "webkitColumnSpan": "",
            "webkitColumnWidth": "",
            "webkitColumns": "",
            "webkitFilter": "",
            "webkitFlex": "",
            "webkitFlexBasis": "",
            "webkitFlexDirection": "",
            "webkitFlexFlow": "",
            "webkitFlexGrow": "",
            "webkitFlexShrink": "",
            "webkitFlexWrap": "",
            "webkitFontFeatureSettings": "",
            "webkitFontSizeDelta": "",
            "webkitFontSmoothing": "",
            "webkitHighlight": "",
            "webkitHyphenateCharacter": "",
            "webkitJustifyContent": "",
            "webkitLineBreak": "",
            "webkitLineClamp": "",
            "webkitLocale": "",
            "webkitLogicalHeight": "",
            "webkitLogicalWidth": "",
            "webkitMarginAfter": "",
            "webkitMarginBefore": "",
            "webkitMarginEnd": "",
            "webkitMarginStart": "",
            "webkitMask": "",
            "webkitMaskBoxImage": "",
            "webkitMaskBoxImageOutset": "",
            "webkitMaskBoxImageRepeat": "",
            "webkitMaskBoxImageSlice": "",
            "webkitMaskBoxImageSource": "",
            "webkitMaskBoxImageWidth": "",
            "webkitMaskClip": "",
            "webkitMaskComposite": "",
            "webkitMaskImage": "",
            "webkitMaskOrigin": "",
            "webkitMaskPosition": "",
            "webkitMaskPositionX": "",
            "webkitMaskPositionY": "",
            "webkitMaskRepeat": "",
            "webkitMaskRepeatX": "",
            "webkitMaskRepeatY": "",
            "webkitMaskSize": "",
            "webkitMaxLogicalHeight": "",
            "webkitMaxLogicalWidth": "",
            "webkitMinLogicalHeight": "",
            "webkitMinLogicalWidth": "",
            "webkitOpacity": "",
            "webkitOrder": "",
            "webkitPaddingAfter": "",
            "webkitPaddingBefore": "",
            "webkitPaddingEnd": "",
            "webkitPaddingStart": "",
            "webkitPerspective": "",
            "webkitPerspectiveOrigin": "",
            "webkitPerspectiveOriginX": "",
            "webkitPerspectiveOriginY": "",
            "webkitPrintColorAdjust": "",
            "webkitRtlOrdering": "",
            "webkitRubyPosition": "",
            "webkitShapeImageThreshold": "",
            "webkitShapeMargin": "",
            "webkitShapeOutside": "",
            "webkitTapHighlightColor": "",
            "webkitTextCombine": "",
            "webkitTextDecorationsInEffect": "",
            "webkitTextEmphasis": "",
            "webkitTextEmphasisColor": "",
            "webkitTextEmphasisPosition": "",
            "webkitTextEmphasisStyle": "",
            "webkitTextFillColor": "",
            "webkitTextOrientation": "",
            "webkitTextSecurity": "",
            "webkitTextSizeAdjust": "",
            "webkitTextStroke": "",
            "webkitTextStrokeColor": "",
            "webkitTextStrokeWidth": "",
            "webkitTransform": "",
            "webkitTransformOrigin": "",
            "webkitTransformOriginX": "",
            "webkitTransformOriginY": "",
            "webkitTransformOriginZ": "",
            "webkitTransformStyle": "",
            "webkitTransition": "",
            "webkitTransitionDelay": "",
            "webkitTransitionDuration": "",
            "webkitTransitionProperty": "",
            "webkitTransitionTimingFunction": "",
            "webkitUserDrag": "",
            "webkitUserModify": "",
            "webkitUserSelect": "",
            "webkitWritingMode": ""
        },
        "white": "",
        "widows": "",
        "width": "",
        "will": "",
        "word": {
            "wordBreak": "",
            "wordSpacing": "",
            "wordWrap": ""
        },
        "writing": "",
        "x": "",
        "y": "",
        "z": "",
        "zoom": ""
                    }
    
}
